### ISSUE TITLE
Table data extraction using Form Recogniser

### ISSUE THREAD

**Issue by jabzer-research** [konfuzio-ai/document-ai-python-sdk#24]
I am trying to extract table data by training different table layout structures. But once the training is completed I am not able to fetch the table data if I am trying to analyze a new file which has a different layout. Is it a limitation from Azure cognitive services.
https://stackoverflow.com/questions/67126554/table-data-extraction-using-form-recogniser

**Comment by al-konfuzio** [comment]
You can use Konfuzio to extract tables from your documents.

```
# pip install konfuzio_sdk
# in the working directory
# konfuzio_sdk init

from konfuzio_sdk.api import get_results_from_segmentation

result = get_results_from_segmentation(doc_id=1111, project_id=111)
# result contains the elements per page
tables_first_page = [r for r in result[0] if r['label'] == 'table']
```
