### ISSUE TITLE
Count number of relevant words per document

### ISSUE THREAD

**Issue by al-konfuzio** [konfuzio-ai/document-ai-python-sdk#4]

**Comment by Goodvinn** [comment]
I have a problem regarding the project initiation with the project() method.

First i get warnings for big file sizes in my data folder (bbox.json5 files) and second the project() method
gets stuck at line 1099 in ssl.py 

i think i can just ignore the warnings, but i dont know what to do with the second problem

**Comment by Goodvinn** [comment]
After some pause & play in debug mode the script stopped with 

Traceback (most recent call last):
  File "C:\Users\woodv\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 37233260 (char 37233259)
python-BaseException

**Comment by al-konfuzio** [comment]
We are working to make the more efficient for big documents.
