### ISSUE TITLE
How to extract a keyword and its page number from a PDF file using NLP?

### ISSUE THREAD

**Issue by jabzer-research** [konfuzio-ai/document-ai-python-sdk#6]
Using a PDF file, how can I extract keywords (Titles) like INTRODUCTION, CASE PRESENTATION, Table 1 along with the page number and save them in an output file from a PDF. 
[https://stackoverflow.com/questions/65529377/how-to-extract-a-keyword-and-its-page-number-from-a-pdf-file-using-nlp
](url)

**Comment by al-konfuzio** [comment]
```
# pip install konfuzio_sdk
# in working directory
# konfuzio_sdk init

from konfuzio_sdk.api import get_document_annotations
    
document_first_annotation = get_document_annotations(document_id=1111)[0]
page_index = document_first_annotation['bbox']['page_index']
keyword = document_first_annotation['offset_string']
```

The object Annotation in the Konfuzio SDK allows to access directly to the keyword string but, at the moment, not directly to the page index. This attribute will be added soon.
An example to access the first annotation in the first training document of your project would be:

```
# pip install konfuzio_sdk
# in working directory
# konfuzio_sdk init

from konfuzio_sdk.data import Project

my_project = Project()

annotations_first_doc = my_project.documents[0].annotations()
first_annotation = annotations_first_doc[0]
keyword = first_annotation.offset_string
```

**Comment by atraining** [comment]
Further code examples can be found here: https://dev.konfuzio.com/sdk/examples/examples.html#create-regex-based-annotations
