### ISSUE TITLE
What is the reason for the 5 sec. delay after an ImportError?

### ISSUE THREAD

**Issue by pchr8** [konfuzio-ai/document-ai-python-sdk#77]
Hi!

I'm referring to this bit: https://github.com/konfuzio-ai/document-ai-python-sdk/blame/master/konfuzio_sdk/settings_importer.py#L20

I'm trying to run tests that import functions from `konfuzio_sdk`, but they take 5 seconds to start due to that delay. And sadly I can't easily add a dummy settings.py to the working directory in my test environment. A similar problem happens when running my application

Do you have any suggestions of how to best deal with that? And - that line is definitely there for a reason, but I'm really curious why. I can't think of anything and this makes me frustrated

Thank you!

**Comment by zypriafl** [comment]
Hi Serhii,

Thanks for brinign this up. Until now the SDK was expected to always start with settings.py. In a previous version the user was shown a warning messages displaying the downsides of not having a settings file. I think its a good idea to remove the 5 seconds delay - we will consider this in the next release.

Best,
Florian

**Comment by pchr8** [comment]
Thank you for your answer! I have no further questions about this topic

**Comment by atraining** [comment]
#79 fixes this - thanks for bringing it up https://github.com/konfuzio-ai/document-ai-python-sdk/blob/evaluation/konfuzio_sdk/settings_importer.py

We'll merge #79 soon.
