### ISSUE TITLE
Entity hierarchies

### ISSUE THREAD

**Issue by jabzer-research** [konfuzio-ai/document-ai-python-sdk#8]
https://stackoverflow.com/questions/62028333/auto-nlp-entity-extraction

The issue concerns entity extraction. Is it possible to tag a keyword under 2 different entities in order to create a hierarchy?

**Comment by al-konfuzio** [comment]
Yes, with Konfuzio you can create a label and associate it to different templates.
For example, you can have "Name" belonging to the template "Sender" and to the template "Receiver".

```
# pip install konfuzio_sdk
# in working directory
# konfuzio_sdk init

from konfuzio_sdk.data import Project, Label

my_project = Project()

# Creation of the Label "Name" in the project templates 1 and 2 
# 1 and 2, here, are the ids of the templates "Sender" and "Receiver" in the project
my_label = Label(my_project, text="Name", templates=[1, 2]).save()

```
